version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: happydoc
    volumes:
      - ./psql_data:/var/lib/postgresql/data

  server:
    image: fengye2018/happydoc:latest
    restart: always
    volumes:
      - ./documents:/app/documents
    ports:
      - "${HAPPYDOC_PORT}:8080"
    environment:
      PORT: 8080
